on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'
name: Make Index
jobs:
  makeIndex:
    name: makeIndex
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - run: |
        bin/makeindex.ps1
    - uses: EndBug/add-and-commit@v10
      with:
        add: 'README.md'
        author_name: make_index-workflow
        author_email: noreply@ci.cd
        message: '(chore): update app index [scoop skip]'
